name: openai_client
description: An unofficial, platform independent, client for accessing different AI models developed by OpenAI.
version: 0.0.4
environment:
  sdk: ">=2.18.2 <3.0.0"

repository: https://github.com/Azzeccagarbugli/openai_client
issue_tracker: https://github.com/Azzeccagarbugli/openai_client/issues
homepage: https://www.francescocoppola.me

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5
  meta: ^1.8.0

dev_dependencies:
  collection: ^1.17.0
  lint: ^2.0.1
  test: ^1.22.1
