name: openai_client
description: >-
  Too Good To Go is a service that connects customers
  to restaurants and stores that have surplus unsold food.
  This is an unofficial client to access their API.
version: 0.0.1
environment:
  sdk: ">=2.18.2 <3.0.0"

repository: https://github.com/Azzeccagarbugli/openai_client
issue_tracker: https://github.com/Azzeccagarbugli/openai_client/issues
homepage: https://www.francescocoppola.me

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5
  meta: ^1.8.0

dev_dependencies:
  lint: ^1.10.0
  test: ^1.16.0
