name: openai_client
description: An unofficial, platform independent, client for accessing different AI models developed by OpenAI.
version: 0.0.8
environment:
  sdk: ">=2.18.2 <3.0.0"

repository: https://github.com/Azzeccagarbugli/openai_client
issue_tracker: https://github.com/Azzeccagarbugli/openai_client/issues
homepage: https://www.francescocoppola.me

screenshots:
  - description: Dart client for accessing different AI models developed by OpenAI.
    path: assets/banner.png

dependencies:
  equatable: ^2.0.5
  http: ^1.1.0
  meta: ^1.8.0

dev_dependencies:
  collection: ^1.17.1
  lint: ^2.0.1
  test: ^1.23.1
